/**
 * Role → permission map (first stable version).
 *
 * Derived from the Recommended Access Matrix in the RBAC spec. This is
 * the *default* grant per role; individual users can extend or revoke
 * permissions via sig_profiles.extra_permissions / revoked_permissions.
 *
 * `super_admin` holds the wildcard and implicitly has every permission.
 * Assignment-scoped access (a planner only seeing *their* clients) is
 * enforced by canAccessClient/canAccessHousehold on top of these grants,
 * not by the permission strings alone.
 */
import { PERMISSIONS as P, WILDCARD_PERMISSION, type Permission } from './permissions';
import { ROLES, type Role } from './roles';

const {
  CLIENTS_VIEW_ASSIGNED, CLIENTS_EDIT, CLIENTS_VIEW_DOCUMENTS, CLIENTS_VIEW_NOTES,
  CLIENTS_VIEW_SERVICE_HISTORY, CLIENTS_VIEW_ALL, CLIENTS_CREATE, CLIENTS_ARCHIVE,
  CLIENTS_ASSIGN_ADVISORS,
  HOUSEHOLDS_VIEW_ASSIGNED, HOUSEHOLDS_VIEW_ALL, HOUSEHOLDS_CREATE, HOUSEHOLDS_EDIT,
  HOUSEHOLDS_ASSIGN_MEMBERS, HOUSEHOLDS_ARCHIVE,
  CONTACTS_VIEW, CONTACTS_CREATE, LEADS_VIEW, LEADS_CREATE, LEADS_ASSIGN, LEADS_CONVERT,
  PROSPECTS_VIEW, PROSPECTS_CREATE, PROSPECTS_ASSIGN, PROSPECTS_CONVERT,
  PLANNER_VIEW_DASHBOARD, TASKS_VIEW, TASKS_CREATE, TASKS_ASSIGN, TASKS_COMPLETE,
  NOTES_VIEW_ADVISOR, NOTES_VIEW_SERVICE, WORKFLOWS_VIEW, WORKFLOWS_UPDATE,
  APPOINTMENTS_VIEW, APPOINTMENTS_CREATE, APPOINTMENTS_EDIT, APPOINTMENTS_CANCEL,
  CALENDARS_VIEW_ALL, CALENDARS_VIEW_ASSIGNED, MEETINGS_VIEW_NOTES, MEETINGS_CREATE_NOTES,
  MEETINGS_EDIT_NOTES,
  EVENTS_VIEW, EVENTS_CREATE, EVENTS_EDIT, EVENTS_MANAGE_REGISTRATIONS, EVENTS_VIEW_ATTENDEES,
  EVENTS_CHECKIN, EVENTS_SEND_REMINDERS, EVENTS_EXPORT_ATTENDEES, EVENTS_REGISTER,
  MARKETING_VIEW_CAMPAIGNS, MARKETING_CREATE_CAMPAIGNS, MARKETING_EDIT_CAMPAIGNS,
  MARKETING_APPROVE_CAMPAIGNS, MARKETING_SEND_CAMPAIGNS, MARKETING_VIEW_LISTS,
  MARKETING_MANAGE_SEGMENTS, MARKETING_MANAGE_TEMPLATES, MARKETING_VIEW_REPORTS,
  DOCUMENTS_VIEW, DOCUMENTS_UPLOAD, DOCUMENTS_DELETE, DOCUMENTS_SHARE, DOCUMENTS_REQUEST,
  DOCUMENTS_VIEW_CLIENT_UPLOADS,
  EMPLOYEE_DOCS_VIEW_OWN, EMPLOYEE_DOCS_UPLOAD_OWN, EMPLOYEE_DOCS_VIEW_ALL,
  EXPENSES_VIEW_OWN, EXPENSES_CREATE, EXPENSES_SUBMIT, EXPENSES_VIEW_ALL,
  EXPENSES_APPROVE, EXPENSES_REIMBURSE, EXPENSES_EXPORT,
  COMMS_VIEW, COMMS_SEND_APPROVED, COMMS_DRAFT, COMMS_APPROVE, COMMS_VIEW_HISTORY,
  COMMS_MANAGE_TEMPLATES,
  AI_USE, AI_VIEW_SUMMARIES, AI_CREATE_DRAFTS, AI_APPROVE_DRAFTS, AI_SEND_MESSAGES,
  AI_MANAGE_SETTINGS, AI_VIEW_AUDIT_LOGS, AI_RUN_LEAD_GEN,
  REPORTS_VIEW, REPORTS_EXPORT, REPORTS_VIEW_FIRM_ANALYTICS, REPORTS_VIEW_ASSIGNED_ANALYTICS,
  REPORTS_VIEW_CAMPAIGN, REPORTS_VIEW_EVENT,
  SETTINGS_VIEW, SETTINGS_EDIT, SETTINGS_MANAGE_INTEGRATIONS, SETTINGS_MANAGE_AUTOMATIONS,
  SETTINGS_MANAGE_BILLING, SETTINGS_MANAGE_COMPLIANCE,
  USERS_VIEW, USERS_INVITE, USERS_ADD, USERS_EDIT, USERS_SUSPEND, USERS_ARCHIVE,
  USERS_ASSIGN_ROLES, USERS_RESET_INVITE, USERS_VIEW_ACTIVITY,
  AUDIT_VIEW, AUDIT_EXPORT,
} = P;

/**
 * Every internal employee logs their own expenses and uploads their own
 * compliance documents. Spread into each internal role. Verifying documents
 * and approving expenses are separate, admin-side grants.
 */
const EMPLOYEE_SELF_SERVICE: Permission[] = [
  EXPENSES_VIEW_OWN, EXPENSES_CREATE, EXPENSES_SUBMIT,
  EMPLOYEE_DOCS_VIEW_OWN, EMPLOYEE_DOCS_UPLOAD_OWN,
];

/** Permissions common to advisor-class roles (assignment-scoped clients). */
const ADVISOR_BASE: Permission[] = [
  ...EMPLOYEE_SELF_SERVICE,
  CLIENTS_VIEW_ASSIGNED, CLIENTS_EDIT, CLIENTS_VIEW_DOCUMENTS, CLIENTS_VIEW_NOTES,
  CLIENTS_VIEW_SERVICE_HISTORY,
  HOUSEHOLDS_VIEW_ASSIGNED,
  CONTACTS_VIEW, LEADS_VIEW, PROSPECTS_VIEW,
  PLANNER_VIEW_DASHBOARD, TASKS_VIEW, TASKS_CREATE, TASKS_COMPLETE, WORKFLOWS_VIEW,
  WORKFLOWS_UPDATE,
  APPOINTMENTS_VIEW, APPOINTMENTS_CREATE, APPOINTMENTS_EDIT, CALENDARS_VIEW_ASSIGNED,
  MEETINGS_VIEW_NOTES, MEETINGS_CREATE_NOTES, MEETINGS_EDIT_NOTES,
  EVENTS_VIEW, EVENTS_REGISTER,
  DOCUMENTS_VIEW, DOCUMENTS_UPLOAD, DOCUMENTS_REQUEST, DOCUMENTS_VIEW_CLIENT_UPLOADS,
  COMMS_VIEW, COMMS_DRAFT, COMMS_SEND_APPROVED, COMMS_VIEW_HISTORY,
  AI_USE, AI_VIEW_SUMMARIES, AI_CREATE_DRAFTS,
  REPORTS_VIEW_ASSIGNED_ANALYTICS,
];

/** Own-portal permissions shared by external client-type roles. */
const CLIENT_PORTAL_BASE: Permission[] = [
  APPOINTMENTS_VIEW, APPOINTMENTS_CREATE,
  DOCUMENTS_VIEW, DOCUMENTS_UPLOAD,
  COMMS_VIEW, COMMS_SEND_APPROVED,
  EVENTS_VIEW, EVENTS_REGISTER,
  TASKS_VIEW, TASKS_COMPLETE,
];

export const ROLE_PERMISSIONS: Record<Role, readonly Permission[] | readonly ['*']> = {
  // ── Internal ─────────────────────────────────────────────
  [ROLES.SUPER_ADMIN]: [WILDCARD_PERMISSION],

  [ROLES.OWNER_LEADERSHIP]: [
    ...EMPLOYEE_SELF_SERVICE,
    EXPENSES_VIEW_ALL, EXPENSES_EXPORT, EMPLOYEE_DOCS_VIEW_ALL,
    CLIENTS_VIEW_ALL, HOUSEHOLDS_VIEW_ALL, CONTACTS_VIEW, LEADS_VIEW, PROSPECTS_VIEW,
    APPOINTMENTS_VIEW, CALENDARS_VIEW_ALL, MEETINGS_VIEW_NOTES,
    EVENTS_VIEW, EVENTS_VIEW_ATTENDEES,
    MARKETING_VIEW_CAMPAIGNS, MARKETING_VIEW_REPORTS,
    COMMS_VIEW, COMMS_VIEW_HISTORY,
    AI_VIEW_SUMMARIES,
    REPORTS_VIEW, REPORTS_EXPORT, REPORTS_VIEW_FIRM_ANALYTICS, REPORTS_VIEW_CAMPAIGN,
    REPORTS_VIEW_EVENT,
    USERS_VIEW, AUDIT_VIEW,
    SETTINGS_VIEW,
    TASKS_VIEW, WORKFLOWS_VIEW,
  ],

  [ROLES.ADMIN]: [
    ...EMPLOYEE_SELF_SERVICE,
    // Admins run the expense workflow, but verifying employee documents and
    // editing the requirement catalog stay with super_admin (wildcard).
    EXPENSES_VIEW_ALL, EXPENSES_APPROVE, EXPENSES_REIMBURSE, EXPENSES_EXPORT,
    EMPLOYEE_DOCS_VIEW_ALL,
    USERS_VIEW, USERS_INVITE, USERS_ADD, USERS_EDIT, USERS_SUSPEND, USERS_RESET_INVITE,
    USERS_VIEW_ACTIVITY,
    CLIENTS_VIEW_ALL, CLIENTS_CREATE, CLIENTS_EDIT, CLIENTS_ARCHIVE, CLIENTS_ASSIGN_ADVISORS,
    CLIENTS_VIEW_DOCUMENTS, CLIENTS_VIEW_NOTES, CLIENTS_VIEW_SERVICE_HISTORY,
    HOUSEHOLDS_VIEW_ALL, HOUSEHOLDS_CREATE, HOUSEHOLDS_EDIT, HOUSEHOLDS_ASSIGN_MEMBERS,
    HOUSEHOLDS_ARCHIVE,
    CONTACTS_VIEW, CONTACTS_CREATE, LEADS_VIEW, LEADS_CREATE, LEADS_ASSIGN, LEADS_CONVERT,
    PROSPECTS_VIEW, PROSPECTS_CREATE, PROSPECTS_ASSIGN, PROSPECTS_CONVERT,
    PLANNER_VIEW_DASHBOARD, TASKS_VIEW, TASKS_CREATE, TASKS_ASSIGN, TASKS_COMPLETE,
    WORKFLOWS_VIEW, WORKFLOWS_UPDATE, NOTES_VIEW_ADVISOR, NOTES_VIEW_SERVICE,
    APPOINTMENTS_VIEW, APPOINTMENTS_CREATE, APPOINTMENTS_EDIT, APPOINTMENTS_CANCEL,
    CALENDARS_VIEW_ALL, MEETINGS_VIEW_NOTES, MEETINGS_CREATE_NOTES, MEETINGS_EDIT_NOTES,
    EVENTS_VIEW, EVENTS_CREATE, EVENTS_EDIT, EVENTS_MANAGE_REGISTRATIONS, EVENTS_VIEW_ATTENDEES,
    EVENTS_CHECKIN, EVENTS_SEND_REMINDERS, EVENTS_EXPORT_ATTENDEES,
    MARKETING_VIEW_CAMPAIGNS, MARKETING_CREATE_CAMPAIGNS, MARKETING_EDIT_CAMPAIGNS,
    MARKETING_SEND_CAMPAIGNS, MARKETING_VIEW_LISTS, MARKETING_MANAGE_SEGMENTS,
    MARKETING_MANAGE_TEMPLATES, MARKETING_VIEW_REPORTS,
    DOCUMENTS_VIEW, DOCUMENTS_UPLOAD, DOCUMENTS_DELETE, DOCUMENTS_SHARE, DOCUMENTS_REQUEST,
    DOCUMENTS_VIEW_CLIENT_UPLOADS,
    COMMS_VIEW, COMMS_DRAFT, COMMS_SEND_APPROVED, COMMS_VIEW_HISTORY, COMMS_MANAGE_TEMPLATES,
    AI_USE, AI_VIEW_SUMMARIES, AI_CREATE_DRAFTS, AI_APPROVE_DRAFTS, AI_RUN_LEAD_GEN,
    REPORTS_VIEW, REPORTS_EXPORT, REPORTS_VIEW_CAMPAIGN, REPORTS_VIEW_EVENT,
    SETTINGS_VIEW,
    AUDIT_VIEW,
  ],

  [ROLES.FINANCIAL_PLANNER]: [
    ...ADVISOR_BASE,
    TASKS_ASSIGN, LEADS_ASSIGN, NOTES_VIEW_ADVISOR, NOTES_VIEW_SERVICE,
    COMMS_APPROVE,
  ],
  [ROLES.WRITING_ADVISOR]: [
    ...ADVISOR_BASE,
    NOTES_VIEW_ADVISOR, COMMS_APPROVE,
  ],
  [ROLES.SERVICING_ADVISOR]: [
    ...ADVISOR_BASE,
    NOTES_VIEW_SERVICE,
  ],
  [ROLES.PLANNER_ADMINISTRATOR]: [
    ...ADVISOR_BASE,
    APPOINTMENTS_CANCEL, DOCUMENTS_SHARE,
  ],
  [ROLES.CLIENT_SERVICE_ASSOCIATE]: [
    ...EMPLOYEE_SELF_SERVICE,
    CLIENTS_VIEW_ASSIGNED, HOUSEHOLDS_VIEW_ASSIGNED,
    TASKS_VIEW, TASKS_CREATE, TASKS_COMPLETE, WORKFLOWS_VIEW, WORKFLOWS_UPDATE,
    NOTES_VIEW_SERVICE,
    APPOINTMENTS_VIEW, APPOINTMENTS_CREATE, APPOINTMENTS_EDIT, CALENDARS_VIEW_ASSIGNED,
    DOCUMENTS_VIEW, DOCUMENTS_UPLOAD, DOCUMENTS_REQUEST, DOCUMENTS_VIEW_CLIENT_UPLOADS,
    COMMS_VIEW, COMMS_SEND_APPROVED, COMMS_VIEW_HISTORY,
    EVENTS_VIEW, AI_USE, AI_VIEW_SUMMARIES,
  ],

  [ROLES.MARKETING_MANAGER]: [
    ...EMPLOYEE_SELF_SERVICE,
    MARKETING_VIEW_CAMPAIGNS, MARKETING_CREATE_CAMPAIGNS, MARKETING_EDIT_CAMPAIGNS,
    MARKETING_APPROVE_CAMPAIGNS, MARKETING_SEND_CAMPAIGNS, MARKETING_VIEW_LISTS,
    MARKETING_MANAGE_SEGMENTS, MARKETING_MANAGE_TEMPLATES, MARKETING_VIEW_REPORTS,
    CONTACTS_VIEW, LEADS_VIEW,
    EVENTS_VIEW, EVENTS_CREATE, EVENTS_EDIT, EVENTS_SEND_REMINDERS,
    COMMS_VIEW, COMMS_DRAFT, COMMS_MANAGE_TEMPLATES, COMMS_VIEW_HISTORY,
    AI_USE, AI_VIEW_SUMMARIES, AI_CREATE_DRAFTS,
    REPORTS_VIEW_CAMPAIGN, TASKS_VIEW,
  ],

  [ROLES.EVENT_COORDINATOR]: [
    ...EMPLOYEE_SELF_SERVICE,
    EVENTS_VIEW, EVENTS_CREATE, EVENTS_EDIT, EVENTS_MANAGE_REGISTRATIONS, EVENTS_VIEW_ATTENDEES,
    EVENTS_CHECKIN, EVENTS_SEND_REMINDERS, EVENTS_EXPORT_ATTENDEES,
    CONTACTS_VIEW, LEADS_VIEW, LEADS_CREATE,
    COMMS_VIEW, COMMS_DRAFT, COMMS_SEND_APPROVED,
    MARKETING_VIEW_CAMPAIGNS,
    TASKS_VIEW, TASKS_CREATE, TASKS_COMPLETE,
    REPORTS_VIEW_EVENT, AI_USE, AI_VIEW_SUMMARIES,
  ],

  [ROLES.COMPLIANCE_REVIEWER]: [
    ...EMPLOYEE_SELF_SERVICE,
    // Compliance reads the firm-wide document picture but does not sign off.
    EMPLOYEE_DOCS_VIEW_ALL, EXPENSES_VIEW_ALL,
    COMMS_VIEW, COMMS_VIEW_HISTORY, COMMS_APPROVE,
    AI_VIEW_SUMMARIES, AI_VIEW_AUDIT_LOGS, AI_APPROVE_DRAFTS,
    MARKETING_VIEW_CAMPAIGNS, MARKETING_APPROVE_CAMPAIGNS,
    CLIENTS_VIEW_ALL, CLIENTS_VIEW_NOTES, CLIENTS_VIEW_DOCUMENTS,
    AUDIT_VIEW, AUDIT_EXPORT,
    REPORTS_VIEW, USERS_VIEW_ACTIVITY,
  ],

  [ROLES.SUPPORT_OPERATIONS]: [
    ...EMPLOYEE_SELF_SERVICE,
    TASKS_VIEW, TASKS_COMPLETE, WORKFLOWS_VIEW, WORKFLOWS_UPDATE,
    DOCUMENTS_VIEW, DOCUMENTS_UPLOAD,
    CONTACTS_VIEW, AI_USE,
  ],

  [ROLES.READ_ONLY]: [
    ...EMPLOYEE_SELF_SERVICE,
    CLIENTS_VIEW_ALL, CLIENTS_VIEW_NOTES, CLIENTS_VIEW_DOCUMENTS, HOUSEHOLDS_VIEW_ALL,
    CONTACTS_VIEW, LEADS_VIEW, PROSPECTS_VIEW,
    APPOINTMENTS_VIEW, EVENTS_VIEW, EVENTS_VIEW_ATTENDEES,
    MARKETING_VIEW_CAMPAIGNS, MARKETING_VIEW_REPORTS,
    COMMS_VIEW_HISTORY,
    REPORTS_VIEW, REPORTS_VIEW_FIRM_ANALYTICS, REPORTS_VIEW_CAMPAIGN, REPORTS_VIEW_EVENT,
    AUDIT_VIEW, AI_VIEW_SUMMARIES, USERS_VIEW_ACTIVITY,
  ],

  // ── External ─────────────────────────────────────────────
  [ROLES.CLIENT]: [...CLIENT_PORTAL_BASE],
  [ROLES.HOUSEHOLD_MEMBER]: [
    DOCUMENTS_VIEW, DOCUMENTS_UPLOAD, COMMS_VIEW, COMMS_SEND_APPROVED,
    EVENTS_VIEW, EVENTS_REGISTER, TASKS_VIEW, TASKS_COMPLETE, APPOINTMENTS_VIEW,
  ],
  [ROLES.PROSPECT]: [
    APPOINTMENTS_VIEW, APPOINTMENTS_CREATE,
    DOCUMENTS_VIEW, DOCUMENTS_UPLOAD,
    COMMS_VIEW, COMMS_SEND_APPROVED,
    EVENTS_VIEW, EVENTS_REGISTER, TASKS_VIEW,
  ],
  [ROLES.REFERRAL_PARTNER]: [
    LEADS_CREATE, COMMS_VIEW, COMMS_SEND_APPROVED, EVENTS_VIEW, EVENTS_REGISTER,
    APPOINTMENTS_CREATE,
  ],
  [ROLES.PROFESSIONAL_PARTNER]: [
    LEADS_CREATE, DOCUMENTS_UPLOAD, COMMS_VIEW, COMMS_SEND_APPROVED,
    EVENTS_VIEW, EVENTS_REGISTER, APPOINTMENTS_CREATE,
  ],
  [ROLES.INVESTMENT_COMMITTEE]: [
    DOCUMENTS_UPLOAD, COMMS_VIEW, COMMS_SEND_APPROVED, APPOINTMENTS_CREATE,
  ],
  [ROLES.VENDOR_PARTNER]: [
    DOCUMENTS_UPLOAD, TASKS_VIEW, COMMS_VIEW, COMMS_SEND_APPROVED, EVENTS_REGISTER,
  ],
  [ROLES.EVENT_GUEST]: [
    EVENTS_VIEW, EVENTS_REGISTER, COMMS_VIEW,
  ],
};
